apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-twin-swim
  namespace: nyc
  labels:
    app: swim-aws-wavelength-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swim-aws-wavelength-app
  template:
    metadata:
      labels:
        app: swim-aws-wavelength-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - us-east-1-wl1-nyc-wlz-1
      tolerations:
      - key: "confluent.io/location"
        operator: "Equal"
        value: "wavelength"
        effect: "NoSchedule"
      containers:
        - name: frontend
          image: ghcr.io/swimos/swim-aws-wavelength:latest
          env:
          - name: KAFKA_BOOTSTRAP_URL
            value: "kafka.nyc.svc.cluster.local:9071"
          ports:
            - containerPort: 9001
            
---
apiVersion: v1
kind: Pod
metadata:
  name: confluent-utility
spec:
  containers:
  - name: confluent-utility
    image: justinrlee/confluent-utility
    ports:
    - containerPort: 80
  
---
apiVersion: v1
kind: Service
metadata:
  name: swim-service
  namespace: nyc
spec:
  type: NodePort
  selector:
    app: swim-aws-wavelength-app
  ports:
    - port: 9001
      targetPort: 9001
      nodePort: 32001
      
      
      
# kubectl exec -it confluent-utility -- /bin/sh
# kafka-topics --bootstrap-server kafka-0.kafka.nyc.svc.cluster.local:9071 --create --topic swim-aws-wavelength-demo
